AWSTemplateFormatVersion: '2010-09-09'
Description: Create a public S3 bucket with public read access

Parameters:
  BucketName:
    Type: String
    Description: Globally unique S3 bucket name

Resources:

  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: false
        IgnorePublicAcls: false
        BlockPublicPolicy: false
        RestrictPublicBuckets: false

  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadGetObject
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource: !Sub "arn:aws:s3:::${WebsiteBucket}/*"

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref WebsiteBucket

  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt WebsiteBucket.Arn

  BucketURL:
    Description: Public URL pattern for objects in the bucket
    Value: !Sub "https://${WebsiteBucket}.s3.${AWS::Region}.amazonaws.com/"